#version: "3.7"
services:
  db:
    image: mysql:8.0
    container_name: Mysql_container
    restart: unless-stopped                      # always unless-stopped
    environment:
      MYSQL_DATABASE: goldenbuy_db            # name of database
      #MYSQL_USER: lamahallip             # the name of user
      #MYSQL_PASSWORD: Leseulallip@1999-         # password for user
      MYSQL_ROOT_PASSWORD: Leseulallip@1999-     # password for user
    ports:
      - '3000:3306'                       # host port 3000 is mapper to docker port 3306
    expose:
      - '3000'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - mysql

# Email server config
  mail:
    image: bytemark/smtp:latest
    container_name: SMTP_container
    restart: always
    environment:
      RELAY_HOST: localhost
      RELAY_PORT: 587
      RELAY_USERNAME: service@goldon.com
      RELAY_PASSWORD: Leseulallip@1999-
    ports:
      - '587:587'

volumes:
  mysql:

networks:
  mysql: